env:
  name: MiniGrid-Empty-Random-6x6-v0  # Gym environment name

seed: 0

agent:
  buffer_capacity:    25000    # max replay buffer size
  batch_size:         256       # minibatch size
  learning_rate:      0.0001    # maps to DQNAgent’s lr
  gamma:              0.9
  epsilon_start:      1.0
  epsilon_final:      0.01
  epsilon_decay:      5000
  target_update_freq: 1000
  use_noisy_net:      False     # Set to True to use NoisyNet exploration

train:
  num_frames:     30000   # total env steps
  eval_interval:  1000    # print avg reward every this many episodes