env:
  name: CartPole-v1  # Gym environment name

seed: 0

agent:
  buffer_capacity:    200000    # max replay buffer size
  batch_size:         256       # minibatch size
  learning_rate:      0.0005    # maps to DQNAgent’s lr
  gamma:              0.99
  epsilon_start:      1.0
  epsilon_final:      0.05
  epsilon_decay:      100000
  target_update_freq: 10000
  use_noisy_net:      False     # Set to True to use NoisyNet exploration

train:
  num_frames:     100000   # total env steps
  eval_interval:  1000    # print avg reward every this many episodes