# configs/agent/sweep_buffer_config.yaml
defaults:
  - override hydra/sweeper: optuna

env:
  name: CartPole-v1  # Gym environment name

seed: 0

agent:
  buffer_capacity: 50000  # Default Wert
  batch_size: 256
  learning_rate: 0.001
  gamma: 0.95
  epsilon_start: 1.0
  epsilon_final: 0.01
  epsilon_decay: 10000
  target_update_freq: 1000
  use_noisy_net: False
  minReward:          -1
  maxReward:          1

train:
  num_frames:   50000 # Kürzer für schnelle Tests
  eval_interval: 1000

# Optuna Konfiguration
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
    direction: maximize
    study_name: buffer_capacity_sweep_v3
    n_trials: 20
    params:
      agent.buffer_capacity: choice(10000, 25000, 50000)
      agent.batch_size: choice(64, 128, 256)
      agent.learning_rate: choice(0.0001, 0.005, 0.001)
      agent.gamma: choice(0.9,0.91,0.92,0.93,0.94,0.95,0.96,0.97,0.98,0.99)
      agent.epsilon_decay: choice(5000, 10000, 20000)
      agent.target_update_freq: choice(500, 1000, 5000)
